### ISSUE TITLE
Unable to install the module on FoundryVTT V9

### ISSUE THREAD

**Issue by DiceAndEasy** [brunocalado/bloodstone#1]
Hi,

Thanks a lot for this module! I tried to install it but I get the following error message when trying to install:

![image](https://user-images.githubusercontent.com/86520580/194773977-63fe5e24-9fed-4922-a2f2-8fe12efe6648.png)

Although it says the module "undefined" was installed, I can't find a module with that name or the Bloodstone name. I'm using Foundry V9.

Is this something you could fix? Thanks for your time!

**Comment by brunocalado** [comment]
> Hi,
> 
> Thanks a lot for this module! I tried to install it but I get the following error message when trying to install:
> 
> ![image](https://user-images.githubusercontent.com/86520580/194773977-63fe5e24-9fed-4922-a2f2-8fe12efe6648.png)
> 
> Although it says the module "undefined" was installed, I can't find a module with that name or the Bloodstone name. I'm using Foundry V9.
> 
> Is this something you could fix? Thanks for your time!

Hi!

This is v10+ module. If you can update to v10 it'll work well.

**Comment by DiceAndEasy** [comment]
Thanks for the answer, makes sense! Unfortunately, I have some other modules that I rely on that don't work in V10 so I can't update at this point.
